name: Deploy gh-pages
on:
      push:
            branches:
                  - main
jobs:
      build-and-deploy:
            runs-on: ubuntu-20.04
            steps:
                  - name: Checkout
                    uses: actions/checkout@master

                  - name: Get npm cache
                    id: cache
                    uses: actions/cache@v2
                    with:
                          path: node_modules
                          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                          restore-keys: |
                                ${{ runner.os }}-node-

                  - name: Install
                    if: steps.cache.outputs.cache-hit != 'true'
                    run: npm install

                  - name: Build
                    run: npm run build

                  - name: Deploy
                    uses: peaceiris/actions-gh-pages@v3
                    with:
                          github_token: ${{ secrets.GITHUB_TOKEN }}
                          publish_dir: ./dist
                  - name: Deploy to Server
                    uses: easingthemes/ssh-deploy@main
                    env:
                          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                          ARGS: "-rltgoDzvO --delete"
                          SOURCE: "./dist/"
                          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                          REMOTE_USER: ${{ secrets.REMOTE_USER }}
                          TARGET: "/var/www/img"
